[package]
name = "steviegoodman/unnamed-project"
description = "No description provided."
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Component = "sleitnick/component@2.4.6"
Cmdr = "evaera/cmdr@1.12.0"
Knit = "sleitnick/knit@1.5.1"
Observers = "sleitnick/observers@0.3.3"
ProfileService = "surnautica/profileservice@1.0.0"
Promise = "evaera/promise@4.0.0"
TableUtil = "sleitnick/table-util@1.2.0"
Timer = "sleitnick/timer@1.1.2"
Trove = "sleitnick/trove@1.4.0"
Signal = "sleitnick/signal@1.5.0"
Waiter = "steviegoodman/waiter@^6.0.0"